export const SET_PROJECTS = "SET_PROJECTS";
export const SET_PROJECTS_FETCHING = "SET_PROJECTS_FETCHING";
export const SET_PROJECT_DETAIL_INFO = "SET_PROJECT_DETAIL_INFO";
export const SET_FETCHING_PROJECT_DETAIL = "SET_FETCHING_PROJECT_DETAIL";
export const UPDATE_PROJECT_IMAGES = "UPDATE_PROJECT_IMAGES";
