# Generated by Django 3.2.5 on 2021-11-27 12:03

from django.db import migrations, models
import image_annotation.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_annotation', '0002_vehicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=image_annotation.models.img_upload_path),
        ),
    ]
