# Generated by Django 3.2.5 on 2021-11-28 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_annotation', '0003_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecoordinate',
            name='vehicle_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='image_vehicle_type', to='image_annotation.vehicletype'),
            preserve_default=False,
        ),
    ]
