# Generated by Django 3.2.5 on 2021-11-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_annotation', '0004_imagecoordinate_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecoordinate',
            name='h',
            field=models.FloatField(default=1.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagecoordinate',
            name='w',
            field=models.FloatField(default=1.1),
            preserve_default=False,
        ),
    ]
