# Generated by Django 3.2.5 on 2021-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_annotation', '0005_auto_20211128_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecoordinate',
            name='annotation_id',
            field=models.CharField(default=1111, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagecoordinate',
            name='color',
            field=models.CharField(default=111, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagecoordinate',
            name='type',
            field=models.CharField(default=111, max_length=20),
            preserve_default=False,
        ),
    ]
