export const SET_IMAGE_ANNOTATION_DETAIL = "SET_IMAGE_ANNOTATION_DETAIL";
export const SET_IMAGE_ANNOTATION_DETAIL_FETCHING =
  "SET_IMAGE_ANNOTATION_DETAIL_FETCHING";
export const SET_VEHICLE_TYPE = "SET_VEHICLE_TYPE";
